version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./psinsightsmasscrawler:/psinsightsmasscrawler
    env_file:
      - '.env'
    depends_on:
      - db
      - redis

  celery-worker:
    build:
      context: .
    command: celery --app psinsightsmasscrawler worker
    env_file:
      - '.env'
    depends_on:
      - app
      - db
      - redis

  db:
    image: postgres:12.4-alpine
    env_file:
      - '.env'

  redis:
    image: redis:6.0.8-alpine
