# Generated by Django 3.2.6 on 2021-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_report',
            field=models.TextField(blank=True),
        ),
    ]
