# Generated by Django 3.2.6 on 2021-08-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_batch_batch_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchurl',
            name='state',
            field=models.CharField(choices=[('WAI', 'Waiting'), ('RUN', 'Running'), ('ERR', 'Error'), ('FIN', 'Finished')], default='WAI', max_length=3),
        ),
    ]
