# Generated by Django 3.2.6 on 2021-08-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_batchurl_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Website',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='site',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='site',
            new_name='website',
        ),
    ]
