# Generated by Django 3.2.6 on 2021-08-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20210804_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchurl',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='state',
            field=models.CharField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Error'), (3, 'Finished')], default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='batchurl',
            name='state',
            field=models.CharField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Error'), (3, 'Finished')], default=0, max_length=3),
        ),
    ]
