# Generated by Django 3.2.6 on 2021-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20210804_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Error'), (3, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='batchurl',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Error'), (3, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='batchurl',
            name='status_code',
            field=models.SmallIntegerField(null=True),
        ),
    ]
