# Generated by Django 3.2.6 on 2021-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20210804_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSpeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
