# Generated by Django 3.2.6 on 2021-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20210807_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchurl',
            name='worker_group',
            field=models.SmallIntegerField(help_text='Worker group of this batch URL', null=True),
        ),
    ]
